MANVIR SANDBOX/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ascension Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Antarctic Territory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Account Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AsiaPAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Hop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

MANVIR SANDBOX/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AWS_Forecast_Category__c</fullName>
        <label>Mavenir Forecast Category</label>
        <picklist>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stretch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Omitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bid_Stage__c</fullName>
        <label>Bid Stage</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ascension Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Antarctic Territory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <label>Programme Manager</label>
        <picklist>
            <picklistValues>
                <fullName>A. Tayler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D. Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H Ghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J. Wells</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R. Haines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V. Kohli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be identified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AsiaPAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Hop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Selling_agent_or_consultant__c</fullName>
        <inlineHelpText>If a 3rd party commission agent/consultant with a current agreement will be paid commission for this deal please select. If an agreement with a 3rd party is probable or still pending please select &apos;Other&apos;. Otherwise select &apos;Not applicable&apos;.</inlineHelpText>
        <label>Selling agent or consultant</label>
        <picklist>
            <picklistValues>
                <fullName>Not applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mostniaga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jetview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buster Burke Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anabatic Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <description>Which Solution best represents this opportunity</description>
        <inlineHelpText>Voice &amp; Video - Converged IP telephony, EIR, UMA, Mobility Server, Media Servers
SMS Solutions - AirMessenger/Gate, IP-SMSC, SMS Policy Engines
IP Messaging - RMS, XDMS,Presence,HTTP g/w,Social Aggregation
Other - not covered by the three solutions</inlineHelpText>
        <label>Solution</label>
        <picklist>
            <picklistValues>
                <fullName>Voice &amp; Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP Messaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIR Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Duration_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <label>Support Duration Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

MANVIR SANDBOX/src/objects/Revenue_Recognition__c.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Type</label>
        <referenceTo>Revenue_Type__c</referenceTo>
        <relationshipLabel>Revenue Recognition</relationshipLabel>
        <relationshipName>Revenue_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Recognition</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Recognition</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MANVIR SANDBOX/src/objects/Revenue_Type__c.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product &amp; Revenue Type</label>
    <nameField>
        <label>Product &amp; Revenue Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product &amp; Revenue Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MANVIR SANDBOX/src/classes/TestUtility.cls
public with sharing class TestUtility {
    public static Opportunity opp;
    public static List<Product2> prodList;
    public static List<Revenue_Type__c> rtList;
    public static List<Revenue_Recognition__c> rrList;
    
    //create account
    public static Account createAccount(){
        
        Account acc = new Account();
        acc.name = 'test';
        insert acc;
        return acc;
    }
    //create opportunity
    public static Opportunity createOpp(){
        
        opp = new Opportunity();
        opp.name = 'test';
        opp.AccountId = createAccount().id;
        opp.Region__c = 'americas';
        opp.Country__c = 'united kingdom';
        opp.Program_Manager__c = 'test';
        opp.Selling_agent_or_consultant__c = 'test';
        opp.CloseDate = Date.today();
        opp.AWS_Forecast_Category__c = 'test';
        opp.stageName = '1. Suspect';
        opp.Bid_Stage__c = 'Qualified';
        opp.Solution__c = 'Instant Messaging';
        opp.Support_Duration_Months__c = 12;
        opp.Delivery_Duration_Months__c = 2;
        opp.Project_Start_Lag_Days__c = 45;
        insert opp;
        return opp;
        
    }
    //create product
    public static List<Product2> createProduct(){
        prodList = new List<Product2>();
        
        Product2 pr1 = new Product2();
        pr1.name = 'Test Product1';
        pr1.Family = 'Test';
        pr1.IsActive = true;
        prodList.add(pr1);
        
        Product2 pr2 = new Product2();
        pr2.name = 'Test Product2';
        pr2.Family = 'Test';
        pr2.IsActive = true;
        prodList.add(pr2);
        
        Product2 pr3 = new Product2();
        pr3.name = 'Test Product3';
        pr3.Family = 'Test';
        pr3.IsActive = true;
        prodList.add(pr3);
        
        insert prodList;
        return prodList;
    }
    
    //create Book_Values__c
    public static List<Book_Values__c>  createBookValues(){ 
        
      List<Book_Values__c> bvList = new List<Book_Values__c>();
      
      Book_Values__c bv1 = new Book_Values__c();
      bv1.Name = 'Lag_Days';
      bv1.Value__c = '45';
      bvList.add(bv1);
      
      Book_Values__c bv2 = new Book_Values__c();
      bv2.Name = 'Month_Duration';
      bv2.Value__c = '3';
      bvList.add(bv2);
      
      Book_Values__c bv3 = new Book_Values__c();
      bv3.Name = 'Support_Month_Duration';
      bv3.Value__c = '12';
      bvList.add(bv3);
      
      insert bvList;
      return bvList;    
     
    }
    //create opportunity
    public static Opportunity createOppWithoutBookValues(){
        
        Opportunity opp1 = new Opportunity();
        opp1.name = 'test';
        opp1.AccountId = createAccount().id;
        opp1.Region__c = 'americas';
        opp1.Country__c = 'united kingdom';
        opp1.Program_Manager__c = 'test';
        opp1.Selling_agent_or_consultant__c = 'test';
        opp1.CloseDate = Date.today();
        opp1.AWS_Forecast_Category__c = 'test';
        opp1.stageName = '1. Suspect';
        opp1.Bid_Stage__c = 'Qualified';
        opp1.Solution__c = 'Instant Messaging';
        insert opp1;
        return opp1;
        
    }
    
    //create OppBudget__c
    public static List<OppBudget__c> createOppBudget(){
        List<OppBudget__c> obList = new List<OppBudget__c>();
        
        OppBudget__c ob1 = new OppBudget__c();
        ob1.name = 'Number_Of_Columns';
        ob1.Value__c = '10';
        obList.add(ob1);
        
        OppBudget__c ob2 = new OppBudget__c();
        ob2.name = 'Number_Of_Rows';
        ob2.Value__c = '10';
        obList.add(ob2);
        
        OppBudget__c ob3 = new OppBudget__c();
        ob3.name = 'Row_1';
        ob3.Value__c = 'Subscribers';
        obList.add(ob3);
        
        OppBudget__c ob4 = new OppBudget__c();
        ob4.name = 'Row_10';
        ob4.Value__c = 'Placeholder5';
        obList.add(ob4);
        
        OppBudget__c ob5 = new OppBudget__c();
        ob5.name = 'Row_2';
        ob5.Value__c = 'HW Price Per Sub';
        obList.add(ob5);
        
        OppBudget__c ob6 = new OppBudget__c();
        ob6.name = 'Row_3';
        ob6.Value__c = 'SW Price per hub';
        obList.add(ob6);
        
        OppBudget__c ob7 = new OppBudget__c();
        ob7.name = 'Row_4';
        ob7.Value__c = 'HW Price % of total HW & SW';
        obList.add(ob7);
        
        OppBudget__c ob8 = new OppBudget__c();
        ob8.name = 'Row_5';
        ob8.Value__c = 'Professional Services price as % of total (HW+SW+All Services)';
        obList.add(ob8);
        
        OppBudget__c ob9 = new OppBudget__c();
        ob9.name = 'Row_6';
        ob9.Value__c = 'Placeholder1';
        obList.add(ob9);
        
        OppBudget__c ob10 = new OppBudget__c();
        ob10.name = 'Row_7';
        ob10.Value__c = 'Placeholder2';
        obList.add(ob10);
        
        OppBudget__c ob11 = new OppBudget__c();
        ob11.name = 'Row_8';
        ob11.Value__c = 'Placeholder3';
        obList.add(ob11);
        
        OppBudget__c ob12 = new OppBudget__c();
        ob12.name = 'Row_9';
        ob12.Value__c = 'Placeholder4';
        obList.add(ob12);
        
        insert obList;
        return obList;
        
    }

}